TurkKizilayi.Web/Controllers/AnasayfaController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Altyapi.Core.Infrastructure;
using Altyapi.Data.Model;
using Altyapi.Data.ViewModel;

namespace TurkKizilayi.Web.Controllers
{
    public class AnasayfaController : Controller
    {
        #region Constructor
        private readonly IYayinRepository _yayinRepository;

        public AnasayfaController(IYayinRepository yayinRepository)
        {
            _yayinRepository = yayinRepository;
        }
        #endregion

        public ActionResult Index()
        {
            var yayinlar = _yayinRepository.GetAll().Where(q => q.AktifMi);
            var enumerable = yayinlar as IList<Yayin> ?? yayinlar.ToList();
            var viewModelAnasayfa = new ViewModelAnasayfa
            {
                ViewModelYayin = (from yayin in enumerable.Take(5)
                                  orderby yayin.YayinTarihi descending
                                  select new ViewModelYayin
                                  {
                                      ID = yayin.ID,
                                      KategoriID = yayin.KategoriId,
                                      KategoriAdi = yayin.Kategori.Ad,
                                      SeoSlugKategori = yayin.Kategori.SeoSlug,
                                      Baslik = yayin.Baslik,
                                      Icerik = yayin.Icerik,
                                      KisaAciklama = yayin.KisaAciklama,
                                      ResimKucuk = yayin.ResimUrlKucuk,
                                      ResimBuyuk = yayin.ResimUrlBuyuk,
                                      Resimler = yayin.Resimler.ToList(),
                                      Durumu = yayin.AktifMi,
                                      Siralama = yayin.Siralama,
                                      SeoSlug = yayin.SeoSlug,
                                      YayinTarihi = yayin.YayinTarihi
                                  }),

                ViewModelSlaytYayin = (from yayin in enumerable.Where(q => q.SlayttaGorunsunMu && q.AktifMi)
                                       orderby yayin.YayinTarihi descending
                                       select new ViewModelSlaytYayin
                                       {
                                           ID = yayin.ID,
                                           KategoriID = yayin.KategoriId,
                                           KategoriAdi = yayin.Kategori.Ad,
                                           SeoSlugKategori = yayin.Kategori.SeoSlug,
                                           Baslik = yayin.Baslik,
                                           KisaAciklama = yayin.KisaAciklama,
                                           ResimKucuk = yayin.ResimUrlKucuk,
                                           ResimBuyuk = yayin.ResimUrlBuyuk,
                                           Siralama = yayin.Siralama,
                                           SeoSlug = yayin.SeoSlug,
                                           YayinTarihi = yayin.YayinTarihi
                                       })
            };

            return View(viewModelAnasayfa);
        }
    }
}

TurkKizilayi.Web/Controllers/IletisimController.cs
using System;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Web.Configuration;
using System.Web.Mvc;
using Altyapi.Data;
using Altyapi.Data.ViewModel;

namespace TurkKizilayi.Web.Controllers
{
    public class IletisimController : Controller
    {
        // GET: Iletisim

        [HttpGet]
        public ActionResult BizeUlasin()
        {
            return View(new ViewModelIletisimFormu());
        }

        [HttpPost]
        public JsonResult BizeUlasin(ViewModelIletisimFormu viewModelIletisimFormu)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var mailMessage = new MailMessage();
                    var senderMail = new MailAddress(WebConfigurationManager.AppSettings["KurumsalEposta"]);
                    var sb = new StringBuilder();
                    mailMessage.To.Add(WebConfigurationManager.AppSettings["KurumsalEposta"]);
                    mailMessage.From = senderMail;
                    mailMessage.Subject = viewModelIletisimFormu.Konu;
                    mailMessage.IsBodyHtml = false;
                    
                    //smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
                    sb.Append("Adı Soyadı: " + viewModelIletisimFormu.Ad);
                    sb.Append(Environment.NewLine);
                    sb.Append("E-Posta: " + viewModelIletisimFormu.Eposta);
                    sb.Append(Environment.NewLine);
                    sb.Append(Environment.NewLine);
                    sb.Append("Mesaj: " + viewModelIletisimFormu.Mesaj);
                    mailMessage.Body = sb.ToString();
                    using (var smtp = new SmtpClient())
                    {
                        smtp.EnableSsl = false;
                        smtp.UseDefaultCredentials = false;
                        smtp.Host = WebConfigurationManager.AppSettings["SmtpHost"];
                        smtp.Port = int.Parse(WebConfigurationManager.AppSettings["SmtpPort"]);
                        smtp.Credentials = new System.Net.NetworkCredential(WebConfigurationManager.AppSettings["KurumsalEposta"], WebConfigurationManager.AppSettings["KurumsalEpostaSifre"]);
                        smtp.Send(mailMessage);
                    }
                    
                    return Json(
                       new ResultJson
                       {
                           Message = "Mesaj Gönderme İşlemi Başarılı.",
                           MType = "success",
                           Title = "Mesaj Gönderildi",
                       });
                }
                catch (Exception ex)
                {
                    return Json(new ResultJson { Message = "Bir Hata Oluştu", MType = "error", Title = "Hata" });
                }
            }
            else
            {
                return Json(new ResultJson { Message = "Lütfen zorunlu alanları doldurunuz.", MType = "error", Title = "Hata" });
            }

        }
    }
}

TurkKizilayi.Web/Controllers/YayinController.cs
using System.Linq;
using System.Web.Mvc;
using Altyapi.Core.Infrastructure;
using Altyapi.Data.ViewModel;

namespace TurkKizilayi.Web.Controllers
{
    public class YayinController : Controller
    {
        #region Constructor
        private readonly IYayinRepository _yayinRepository;
        private readonly IKategoriRepository _kategoriRepository;

        public YayinController(IYayinRepository yayinRepository, IKategoriRepository kategoriRepository)
        {
            _yayinRepository = yayinRepository;
            _kategoriRepository = kategoriRepository;
        }
        #endregion

        // GET: Yayin
        public ActionResult Kategori(string slugKategori)
        {
            var viewModelYayin = (from yayin in _yayinRepository.
                                  GetMany(q => q.Kategori.SeoSlug == slugKategori)
                orderby yayin.YayinTarihi descending
                select new ViewModelYayin
                {
                    ID = yayin.ID,
                    KategoriID = yayin.KategoriId,
                    KategoriAdi = yayin.Kategori.Ad,
                    SeoSlugKategori = yayin.Kategori.SeoSlug,
                    Baslik = yayin.Baslik,
                    Icerik = yayin.Icerik,
                    KisaAciklama = yayin.KisaAciklama,
                    ResimKucuk = yayin.ResimUrlKucuk,
                    ResimBuyuk = yayin.ResimUrlBuyuk,
                    Resimler = yayin.Resimler.ToList(),
                    Durumu = yayin.AktifMi,
                    Siralama = yayin.Siralama,
                    SeoSlug = yayin.SeoSlug,
                    YayinTarihi = yayin.YayinTarihi
                });
            ViewBag.KategoriAdi = _kategoriRepository.Get(q => q.SeoSlug == slugKategori).Ad;
            return View(viewModelYayin);
        }

        public ActionResult Ziyaretler()
        {
            var viewModelYayin = (from yayin in _yayinRepository.
                                  GetMany(q => q.Kategori.SeoSlug == "ziyaretler")
                                  orderby yayin.YayinTarihi descending
                                  select new ViewModelYayin
                                  {
                                      ID = yayin.ID,
                                      KategoriID = yayin.KategoriId,
                                      KategoriAdi = yayin.Kategori.Ad,
                                      SeoSlugKategori = yayin.Kategori.SeoSlug,
                                      Baslik = yayin.Baslik,
                                      Icerik = yayin.Icerik,
                                      KisaAciklama = yayin.KisaAciklama,
                                      ResimKucuk = yayin.ResimUrlKucuk,
                                      ResimBuyuk = yayin.ResimUrlBuyuk,
                                      Resimler = yayin.Resimler.ToList(),
                                      Durumu = yayin.AktifMi,
                                      Siralama = yayin.Siralama,
                                      SeoSlug = yayin.SeoSlug,
                                      YayinTarihi = yayin.YayinTarihi
                                  });
            ViewBag.KategoriAdi = _kategoriRepository.Get(q => q.SeoSlug == "ziyaretler").Ad;
            return View(viewModelYayin);
        }

        public ActionResult YayinDetay(string slugUrl,string slugKategori)
        {
            var cyayin =  _yayinRepository.Get(q => q.SeoSlug == slugUrl&&q.Kategori.SeoSlug==slugKategori);
            var viewModelYayinlar = (from yayin in _yayinRepository.GetAll()
                                  orderby yayin.YayinTarihi descending
                                  select new ViewModelYayin
                                  {
                                      ID = yayin.ID,
                                      KategoriID = yayin.KategoriId,
                                      KategoriAdi = yayin.Kategori.Ad,
                                      SeoSlugKategori = yayin.Kategori.SeoSlug,
                                      Baslik = yayin.Baslik,
                                      Icerik = yayin.Icerik,
                                      KisaAciklama = yayin.KisaAciklama,
                                      ResimKucuk = yayin.ResimUrlKucuk,
                                      ResimBuyuk = yayin.ResimUrlBuyuk,
                                      Resimler = yayin.Resimler.ToList(),
                                      Durumu = yayin.AktifMi,
                                      Siralama = yayin.Siralama,
                                      SeoSlug = yayin.SeoSlug,
                                      YayinTarihi = yayin.YayinTarihi
                                  }).Take(3);
            ViewBag.SonYayinlar = viewModelYayinlar;
            ViewBag.KategoriAdi = _kategoriRepository.Get(q => q.SeoSlug == slugKategori).Ad;
            if (cyayin == null)
            {
                return View(new ViewModelYayin());
            }
            else
            {
                var viewModelYayin = new ViewModelYayin
                {
                    ID = cyayin.ID,
                    KategoriID = cyayin.KategoriId,
                    KategoriAdi = cyayin.Kategori.Ad,
                    Baslik = cyayin.Baslik,
                    Icerik = cyayin.Icerik,
                    KisaAciklama = cyayin.KisaAciklama,
                    ResimKucuk = cyayin.ResimUrlKucuk,
                    ResimBuyuk = cyayin.ResimUrlBuyuk,
                    Resimler = cyayin.Resimler.ToList(),
                    Durumu = cyayin.AktifMi,
                    Siralama = cyayin.Siralama,
                    SeoSlug = cyayin.SeoSlug,
                    YayinTarihi = cyayin.YayinTarihi
                };
                return View(viewModelYayin);
            }
           
        }
    }
}

TurkKizilayi.Web/Controllers/YonetimController.cs
using System.Web.Mvc;

namespace TurkKizilayi.Web.Controllers
{
    public class YonetimController : Controller
    {
        // GET: Yonetim
        public ActionResult Baskan()
        {
            return View();
        }

        public ActionResult YonetimKurulu()
        {
            return View();
        }

        public ActionResult SubeBilgisi()
        {
            return View();
        }
    }
}

TurkKizilayi.Web/Views/Shared/_BilgiMesaj.cshtml
<div style="background-color:#e10000;padding:20px 10px;">
    <div class="container">

        <div class="row">
            <div class="col-md-3 text-center" style="padding:10px 0px;">
                <img src="~/Content/img/ico-bagis-hatti.png" alt="Bağış Hattı" />
            </div>

            <div class="col-md-3 text-center" style="padding:10px 0px;">
                <img src="~/Content/img/ico-cagri-merkezi.png" alt="Çağrı Merkezi"/>
            </div>

            <div class="col-md-3 text-center" style="padding:10px 0px;">
                <img src="~/Content/img/ico-kan-bagisi.png" alt="Kan Bağışı"/>
            </div>

            <div class="col-md-3 text-center" style="padding:10px 0px;">
                <img src="~/Content/img/ico-online-bagis.png" alt="Online Bağış"/>
            </div>

        </div>

    </div>
</div>

TurkKizilayi.Web/Views/Shared/_Carosel.cshtml
@model IEnumerable<Altyapi.Data.ViewModel.ViewModelSlaytYayin>
<div class="slider-container rev_slider_wrapper">
    <div id="revolutionSlider" class="slider rev_slider" data-plugin-revolution-slider data-plugin-options='{"gridwidth": auto, "gridheight": 500}'>
        <ul>
            @foreach (var slayt in Model)
            {
                <li data-transition="fade">
                    <img src=@slayt.ResimBuyuk
                         alt="@slayt.Baslik"
                         data-bgposition="center center"
                         data-bgfit="cover"
                         data-bgrepeat="no-repeat"
                         class="rev-slidebg">

                    <div class="tp-caption bottom-label" style="background-color: rgba(0, 0, 0, 0.5); opacity: 0.3 !important; width: 100%; padding: 20px;"
                         data-x="100"
                         data-y="400"
                         data-start="1000"
                         data-transform_in="y:[100%];opacity:0;s:500;"><a style="color: whitesmoke;" href=@Url.Action("YayinDetay", "Yayin", new {slugUrl = slayt.SeoSlug, slugKategori = slayt.SeoSlugKategori})>@slayt.Baslik</a>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

TurkKizilayi.Web/Views/Shared/_Footer.cshtml
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="footer-ribbon">
                <span>Bize Ulaşın</span>
            </div>
            <div class="col-md-3">
                <div class="newsletter">
                    <h4>İlgili Bağlantılar</h4>
                    <ul class="contact">
                        <li><a href="http://afetyonetimi.kizilay.org.tr/">Afet Yönetimi</a></li>
                        <li><a href="http://www.kanver.org/" class="cz-color-16777215">Kan Hizmetleri</a></li>
                        <li><a href="http://www.kizilaysaglikgrubu.com/">Teşhis ve Tedavi Hizmetleri</a></li>
                        <li><a href="http://www.kizilaymagaza.org.tr/">Kızılay Mağaza</a></li>
                        <li><a href="http://genclikhizmetleri.kizilay.org.tr/Default.aspx?menuID=895">Gençlik Hizmetleri</a></li>
                        <li><a href="http://www.kizilaymadensuyu.com.tr/">Kızılay Mineralli Su</a></li>
                        <li><a href="http://arsiv.kizilay.org.tr/">Kızılay Arşiv ve Kütüphanesi</a></li>
                        <li><a href="http://www.ilkyardim.org.tr/">İlk Yardım Sitesi</a></li>
                        <li><a href="http://www.kizilayhuzurevi.org.tr/">Kızılay Huzurevi (İstanbul)</a></li>
                        <li><a href="http://www.kizilaykariyer.com/">Kızılay Kariyer (İş Başvurusu)</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-3">
                <div class="newsletter">
                    <h4>Kategoriler</h4>
                    <ul class="contact">
                        <li><a href="@Url.Action("Kategori", "Yayin", new {slugKategori = "etkinlikler"})">Etkinlikler</a></li>
                        <li><a href="@Url.Action("Kategori", "Yayin", new {slugKategori = "duyurular"})">Duyurular</a></li>
                        <li><a href="@Url.Action("Kategori","Yayin",new {slugKategori="yararli-bilgiler"})">Yararlı Bilgiler</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4">
                <div class="contact-details">
                    <h4>Bize Ulaşın</h4>
                    <ul class="contact">
                        <li><p><i class="fa fa-map-marker"></i> <strong>Adres:</strong> Fabrikalar Mah. 3002 Sk. Kızılay Parkı No:2/1</p></li>
                        <li><p><i class="fa fa-phone"></i> <strong>Tel:</strong> 0 (242) 345 46 46</p></li>
                        <li><p><i class="fa fa-envelope"></i> <strong>E-posta:</strong> <a href="mailto:bilgi@turkkizilayikepez.org">bilgi@turkkizilayikepez.org</a></p></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <h4>Takip Edin</h4>
                <ul class="social-icons">
                    <li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-1 text-center">
                    <a href="index.html" class="logo">
                        <img alt="Türk Kızılayı Kepez Şubesi" class="img-responsive" src="~/Content/img/logo_gray.png">
                    </a>
                </div>
                <div class="col-md-7">
                    <p>© Copyright @DateTime.Now.Year. Tüm Hakları saklıdır.</p>
                </div>
                <div class="col-md-4">
                    <nav id="sub-menu">
                        <ul>
                            <li><a href="#">S.S.S.</a></li>
                            <li><a href="#">Site Haritası</a></li>
                            <li><a href="@Url.Action("BizeUlasin","Iletisim")">İletişim</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</footer>

TurkKizilayi.Web/Views/Shared/_Header.cshtml
@using TurkKizilayi.Web.Helpers
<header id="header" data-plugin-options='{"stickyEnabled": true, "stickyEnableOnBoxed": true, "stickyEnableOnMobile": true, "stickyStartAt": 40, "stickySetTop": "-10px", "stickyChangeLogo": true}'>
    <div class="header-body">
        <div class="header-container container">
            <div class="header-row">
                <div class="header-column">
                    <div class="header-logo">
                        <a href="@Url.Action("Index","Anasayfa")">
                            <img alt="Porto" width="121" height="100" data-sticky-width="72" data-sticky-height="60" data-sticky-top="15" src="~/Content/img/logo.png">
                        </a>
                    </div>
                </div>
                <div class="header-column">
                    <div class="header-row">
                        <div class="header-nav">
                            <button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main">
                                <i class="fa fa-bars"></i>
                            </button>
                            <div class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1 collapse">
                                <nav>
                                    <ul class="nav nav-pills" id="mainNav">
                                        <li class="dropdown">
                                            <a class="dropdown-toggle" href="#">
                                                KURUMSAL
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a href="@Url.Action("Baskan","Yonetim")">Başkan</a></li>
                                                <li><a href="@Url.Action("YonetimKurulu","Yonetim")">Yönetim Kurulu</a></li>
                                                <li><a href="@Url.Action("SubeBilgisi", "Yonetim")">Kepez Şubesi</a></li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Kategori","Yayin",new { slugKategori="etkinlikler"})">
                                                ETKİNLİK
                                            </a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Kategori","Yayin",new { slugKategori="duyurular"})">
                                                DUYURU
                                            </a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Kategori","Yayin",new { slugKategori="yararli-bilgiler"})">
                                                YARARLI BİLGİLER
                                            </a>
                                        </li>
                                        <li>
                                            <a href="https://www.kizilay.org.tr/bagis/">
                                                BAĞIŞ YAP
                                            </a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("BizeUlasin","Iletisim")">
                                                İLETİŞİM
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

TurkKizilayi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
          "http://www.w3.org/TR/html4/strict.dtd" lang="tr">
<html lang="tr">
<head>

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Türk Kızılayı-Antalya Kepez Şubesi</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="~/Content/img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=5.0">

    <!-- Web Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/Scripts/font-awesome/css/font-awesome.min.css">

    @Styles.Render("~/css")
    <!-- Scripts CSS -->
    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Scripts/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Scripts/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="~/Scripts/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Scripts/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Scripts/magnific-popup/magnific-popup.css">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Content/css/theme.css">
    <link rel="stylesheet" href="~/Content/css/theme-elements.css">
    <link rel="stylesheet" href="~/Content/css/theme-blog.css">
    <link rel="stylesheet" href="~/Content/css/theme-animate.css">

    <!-- Current Page CSS -->
    <link rel="stylesheet" href="~/Scripts/rs-plugin/css/settings.css" media="screen">
    <link rel="stylesheet" href="~/Scripts/rs-plugin/css/layers.css" media="screen">
    <link rel="stylesheet" href="~/Scripts/rs-plugin/css/navigation.css" media="screen">
    <link rel="stylesheet" href="~/Scripts/circle-flip-slideshow/css/component.css" media="screen">
    <link rel="stylesheet" href="~/Scripts/pnotify/pnotify.css" />
    <!-- Skin CSS -->
    <link rel="stylesheet" href="~/Content/css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Content/css/custom.css">

    <!-- Head Libs -->
    <script src="~/Scripts/modernizr/modernizr.js"></script>*@

</head>
<body>
    <div class="body">

        @Html.Partial("_Header")

        @RenderSection("Carosel", false)

        <div role="main" class="main">

            @RenderBody()

        </div>

        @RenderSection("SonYayinlar", false)

        @Html.Partial("_BilgiMesaj")

        @Html.Partial("_Footer")

    </div>
    @Scripts.Render("~/js")
    @*<!-- Scripts -->
    <script src="~/Scripts/jquery/jquery.min.js"></script>
    <script src="~/Scripts/jquery.appear/jquery.appear.js"></script>
    <script src="~/Scripts/jquery.easing/jquery.easing.js"></script>
    <script src="~/Scripts/jquery-cookie/jquery-cookie.js"></script>
    <script src="~/Scripts/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/common/common.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.gmap/jquery.gmap.js"></script>
    <script src="~/Scripts/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/Scripts/magnific-popup/jquery.magnific-popup.js"></script>
    <script src="~/Scripts/pnotify/pnotify.js"></script>
    <script src="~/Scripts/jquery.form.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <!-- Theme Base, Components and Settings -->
    <script src="~/Scripts/theme.js"></script>

    <!-- Current Page Scripts and Views -->
    <script src="~/Scripts/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/Scripts/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
    <script src="~/Scripts/circle-flip-slideshow/js/jquery.flipshow.js"></script>
    <script src="~/Scripts/views/view.home.js"></script>*@
    <script src="~/Scripts/jquery.gmap/jquery.gmap.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCy_T3Tyh8Mt1x0E422NvP7wVZ971AYDo0&callback=initMap&language=tr&region=TR"></script>
    @*<!-- Theme Custom -->
    <script src="~/Scripts/custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="~/Scripts/theme.init.js"></script>*@

    <!-- Google Analytics -->
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-83422538-1', 'auto');
        ga('send', 'pageview');
    </script>
    <!-- End Google Analytics -->

</body>
</html>

TurkKizilayi.Web/Views/Shared/_SonYayinlar.cshtml
@model IEnumerable<Altyapi.Data.ViewModel.ViewModelYayin>

<div class="container MinHeight">

    <div class="row">
        <div class="col-md-12">
            <div class="blog-posts">
                @if (!Model.Any())
                {
                    <span>Şu anda gösterilecek herhangi bir haber bulunmamaktadır.</span>
                }

                @foreach (var yayin in Model)
                {

                    <article class="post post-medium">
                        <div class="row">

                            <div class="col-md-3">
                                <div class="post-image">

                                    <div>
                                        <div class="img-thumbnail">
                                            <img class="img-responsive" src="@yayin.ResimKucuk" alt="@yayin.Baslik">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-9">

                                <div class="post-content">

                                    <h2>
                                        <a href="@Url.Action("YayinDetay", "Yayin",new {slugUrl = yayin.SeoSlug, slugKategori = yayin.SeoSlugKategori})">@yayin.Baslik</a>
                                    </h2>
                                    <p>@yayin.KisaAciklama...</p>

                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="post-meta PadLeft10px">
                                    <span><i class="fa fa-calendar"></i>@yayin.YayinTarihi.ToString("dd MMMM yyyy") </span>
                                    <a href="@Url.Action("YayinDetay", "Yayin", new {slugUrl = yayin.SeoSlug, slugKategori = yayin.SeoSlugKategori})" class="btn btn-xs btn-primary pull-right">Devamını Oku...</a>
                                </div>
                            </div>
                        </div>

                    </article>

                }

            </div>
        </div>
    </div>
</div>