TurkKizilayi.Web/Areas/KizilayAdmin/Controllers/KategoriController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Altyapi.Core.Infrastructure;
using Altyapi.Data;
using Altyapi.Data.Model;
using Altyapi.Data.ViewModel;
using TurkKizilayi.Web.CustomFilter;

namespace TurkKizilayi.Web.Areas.KizilayAdmin.Controllers
{
    [LoginFilter]
    public class KategoriController : Controller
    {
        #region Constructor
        private readonly IKategoriRepository _kategoriRepository;
        private readonly IKullaniciRepository _kullaniciRepository;

        public KategoriController(IKategoriRepository kategoriRepository, IKullaniciRepository kullaniciRepository)
        {
            _kategoriRepository = kategoriRepository;
            _kullaniciRepository = kullaniciRepository;
        }
        #endregion

        [HttpGet]
        public ActionResult Listele()
        {
            var viewModelKategori = from kategori in _kategoriRepository.GetAll().AsEnumerable()
                                    orderby kategori.ID descending
                                    select new ViewModelKategori
                                    {
                                        ID = kategori.ID,
                                        Ad = kategori.Ad,
                                        Durumu = kategori.AktifMi,
                                        Siralama = kategori.Siralama
                                    };
            return View(viewModelKategori);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            return View(new ViewModelKategori());
        }

        [HttpPost]
        public JsonResult Ekle(ViewModelKategori viewModelKategori)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _kategoriRepository.Insert(PreEkleGuncelle(viewModelKategori));
                    _kategoriRepository.Save();

                    return Json(
                        new ResultJson
                        {
                            Message = "Kategori ekleme işlemi başarılı.",
                            MType = "success",
                            Title = "Kategori Eklendi",
                            RedirectURL = "/KizilayAdmin/Kategori/Listele"
                        });
                }
                else
                {
                    return Json(new ResultJson { Message = "Lütfen zorunlu alanları doldurunuz.", MType = "error", Title = "Hata" });
                }
            }
            catch (Exception ex)
            {
                return Json(new ResultJson { Message = "Bir Hata Oluştu :" +ex, MType = "error", Title = "Hata" });
            }
        }

        [HttpGet]
        public ActionResult Guncelle(int ID)
        {
            var kategori = _kategoriRepository.GetById(ID);
            if (kategori == null)
            {
                throw new Exception("Kategori kayıt bulunamadı.");
            }
            return View(new ViewModelKategori() { ID = kategori.ID, Ad = kategori.Ad, Durumu = kategori.AktifMi, Siralama = kategori.Siralama });
        }

        [HttpPost]
        public JsonResult Guncelle(ViewModelKategori viewModelKategori)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _kategoriRepository.Update(PreEkleGuncelle(viewModelKategori));
                    _kategoriRepository.Save();

                    return Json(
                      new ResultJson
                      {
                          Message = "Kategori güncelleme işlemi başarılı.",
                          MType = "success",
                          Title = "Kategori Güncellendi",
                          RedirectURL = "/KizilayAdmin/Kategori/Listele"
                      });
                }
                else
                {
                    return Json(new ResultJson { Message = "Lütfen zorunlu alanları doldurunuz.", MType = "error", Title = "Hata" });
                }
            }
            catch (Exception ex)
            {
                return Json(new ResultJson { Message = "Bir Hata Oluştu :" + ex, MType = "error", Title = "Hata" });
            }
        }

        [HttpPost]
        public ActionResult Sil(int ID)
        {
            var kategori = _kategoriRepository.GetById(ID);
            if (kategori == null)
            {
                return Json(new ResultJson { Message = "Kategori silmede kayıt bulunamadı", MType = "error", Title = "Hata" });
            }
            _kategoriRepository.Delete(kategori);
            _kategoriRepository.Save();

            return Json(new ResultJson { Message = "Kategori silme işlemi başarılı.", MType = "success", Title = "Kategori Silindi" });
        }

        #region PreEkleGuncelle Kategori
        public Kategori PreEkleGuncelle(ViewModelKategori viewModelKategori)
        {
            var kategori = new Kategori();
            var sessionID = Session["KullaniciAdi"].ToString();
            var kullaniciID= _kullaniciRepository.Get(x => x.KullaniciAdi == sessionID && x.AktifMi == true).ID;
            if (viewModelKategori.ID == 0)
            {
                kategori.EklenmeTarihi = DateTime.Now;
                kategori.Siralama = _kategoriRepository.Count() == 0 ? 1 : _kategoriRepository.GetAll().OrderByDescending(q => q.Siralama).Max(q => q.Siralama) + 1;
            }
            else
            {
                kategori = _kategoriRepository.GetById(viewModelKategori.ID);
                kategori.DegistirmeTarihi = DateTime.Now;
                kategori.GuncelleyenKullaniciId = kullaniciID;
                kategori.Versiyon = kategori.Versiyon + 1;
            }

            kategori.Ad = viewModelKategori.Ad;
            kategori.AktifMi = viewModelKategori.Durumu;
            kategori.SeoSlug = StringManager.ToSlug(viewModelKategori.Ad);
            kategori.EkleyenKullaniciId = kullaniciID;

            return kategori;
        }

        #endregion

        protected override void Dispose(bool disposing)
        {
            _kategoriRepository.Dispose();
            base.Dispose(disposing);
        }
    }
}

TurkKizilayi.Web/Areas/KizilayAdmin/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Altyapi.Core.Infrastructure;
using Altyapi.Data;
using Altyapi.Data.Model;
using Altyapi.Data.ViewModel;
using TurkKizilayi.Web.CustomFilter;

namespace TurkKizilayi.Web.Areas.KizilayAdmin.Controllers
{
    [LoginFilter]
    public class RolController : Controller
    {
        #region Constructor
        private readonly IRolRepository _rolRepository;
        private readonly IKullaniciRepository _kullaniciRepository;

        public RolController(IRolRepository rolRepository, IKullaniciRepository kullaniciRepository)
        {
            _rolRepository = rolRepository;
            _kullaniciRepository = kullaniciRepository;
        }
        #endregion

        [HttpGet]
        public ActionResult Listele()
        {
            var viewModelRol = from rol in _rolRepository.GetAll().AsEnumerable()
                                    orderby rol.ID descending
                                    select new ViewModelRol
                                    {
                                        ID = rol.ID,
                                        Ad = rol.Ad,
                                        Durumu = rol.AktifMi
                                    };
            return View(viewModelRol);
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            return View(new ViewModelRol());
        }

        [HttpPost]
        public JsonResult Ekle(ViewModelRol viewModelRol)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _rolRepository.Insert(PreEkleGuncelle(viewModelRol));
                    _rolRepository.Save();

                    return Json(
                        new ResultJson
                        {
                            Message = "Rol ekleme işlemi başarılı.",
                            MType = "success",
                            Title = "Rol Eklendi",
                            RedirectURL = "/KizilayAdmin/Rol/Listele"
                        });
                }
                else
                {
                    return Json(new ResultJson { Message = "Lütfen zorunlu alanları doldurunuz.", MType = "error", Title = "Hata" });
                }
            }
            catch (Exception ex)
            {
                return Json(new ResultJson { Message = "Bir Hata Oluştu :" + ex, MType = "error", Title = "Hata" });
            }
        }

        [HttpGet]
        public ActionResult Guncelle(int ID)
        {
            var rol = _rolRepository.GetById(ID);
            if (rol == null)
            {
                throw new Exception("Rol kayıt bulunamadı.");
            }
            return View(new ViewModelRol() { ID = rol.ID, Ad = rol.Ad, Durumu = rol.AktifMi});
        }

        [HttpPost]
        public JsonResult Guncelle(ViewModelRol viewModelRol)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _rolRepository.Update(PreEkleGuncelle(viewModelRol));
                    _rolRepository.Save();

                    return Json(
                      new ResultJson
                      {
                          Message = "Rol güncelleme işlemi başarılı.",
                          MType = "success",
                          Title = "Rol Güncellendi",
                          RedirectURL = "/KizilayAdmin/Rol/Listele"
                      });
                }
                else
                {
                    return Json(new ResultJson { Message = "Lütfen zorunlu alanları doldurunuz.", MType = "error", Title = "Hata" });
                }
            }
            catch (Exception ex)
            {
                return Json(new ResultJson { Message = "Bir Hata Oluştu :" + ex, MType = "error", Title = "Hata" });
            }
        }

        [HttpPost]
        public ActionResult Sil(int ID)
        {
            var rol = _rolRepository.GetById(ID);
            if (rol == null)
            {
                return Json(new ResultJson { Message = "Rol silmede kayıt bulunamadı", MType = "error", Title = "Hata" });
            }
            _rolRepository.Delete(rol);
            _rolRepository.Save();

            return Json(new ResultJson { Message = "Rol silme işlemi başarılı.", MType = "success", Title = "Rol Silindi" });
        }

        #region PreEkleGuncelle Rol
        public Rol PreEkleGuncelle(ViewModelRol viewModelRol)
        {
            var rol = new Rol();
            var sessionID = Session["KullaniciAdi"].ToString();
            var kullaniciID = _kullaniciRepository.Get(x => x.KullaniciAdi == sessionID && x.AktifMi == true).ID;
            if (viewModelRol.ID == 0)
            {
                rol.EklenmeTarihi = DateTime.Now;
            }
            else
            {
                rol = _rolRepository.GetById(viewModelRol.ID);
                rol.DegistirmeTarihi = DateTime.Now;
                rol.GuncelleyenKullaniciId = kullaniciID;
                rol.Versiyon = rol.Versiyon + 1;
            }

            rol.Ad = viewModelRol.Ad;
            rol.AktifMi = viewModelRol.Durumu;
            rol.EkleyenKullaniciId = kullaniciID;

            return rol;
        }

        #endregion

        protected override void Dispose(bool disposing)
        {
            _rolRepository.Dispose();
            base.Dispose(disposing);
        }
    }
}

TurkKizilayi.Web/Controllers/YayinController.cs
using System.Linq;
using System.Web.Mvc;
using Altyapi.Core.Infrastructure;
using Altyapi.Data.ViewModel;

namespace TurkKizilayi.Web.Controllers
{
    public class YayinController : Controller
    {
        #region Constructor
        private readonly IYayinRepository _yayinRepository;
        private readonly IKategoriRepository _kategoriRepository;

        public YayinController(IYayinRepository yayinRepository, IKategoriRepository kategoriRepository)
        {
            _yayinRepository = yayinRepository;
            _kategoriRepository = kategoriRepository;
        }
        #endregion

        // GET: Yayin
        public ActionResult Kategori(string slugKategori)
        {
            var viewModelYayin = (from yayin in _yayinRepository.
                                  GetMany(q => q.Kategori.SeoSlug == slugKategori)
                orderby yayin.YayinTarihi descending
                select new ViewModelYayin
                {
                    ID = yayin.ID,
                    KategoriID = yayin.KategoriId,
                    KategoriAdi = yayin.Kategori.Ad,
                    SeoSlugKategori = yayin.Kategori.SeoSlug,
                    Baslik = yayin.Baslik,
                    Icerik = yayin.Icerik,
                    KisaAciklama = yayin.KisaAciklama,
                    ResimKucuk = yayin.ResimUrlKucuk,
                    ResimBuyuk = yayin.ResimUrlBuyuk,
                    Resimler = yayin.Resimler.ToList(),
                    Durumu = yayin.AktifMi,
                    Siralama = yayin.Siralama,
                    SeoSlug = yayin.SeoSlug,
                    YayinTarihi = yayin.YayinTarihi
                });
            ViewBag.KategoriAdi = _kategoriRepository.Get(q => q.SeoSlug == slugKategori).Ad;
            return View(viewModelYayin);
        }

        public ActionResult Ziyaretler()
        {
            var viewModelYayin = (from yayin in _yayinRepository.
                                  GetMany(q => q.Kategori.SeoSlug == "ziyaretler")
                                  orderby yayin.YayinTarihi descending
                                  select new ViewModelYayin
                                  {
                                      ID = yayin.ID,
                                      KategoriID = yayin.KategoriId,
                                      KategoriAdi = yayin.Kategori.Ad,
                                      SeoSlugKategori = yayin.Kategori.SeoSlug,
                                      Baslik = yayin.Baslik,
                                      Icerik = yayin.Icerik,
                                      KisaAciklama = yayin.KisaAciklama,
                                      ResimKucuk = yayin.ResimUrlKucuk,
                                      ResimBuyuk = yayin.ResimUrlBuyuk,
                                      Resimler = yayin.Resimler.ToList(),
                                      Durumu = yayin.AktifMi,
                                      Siralama = yayin.Siralama,
                                      SeoSlug = yayin.SeoSlug,
                                      YayinTarihi = yayin.YayinTarihi
                                  });
            ViewBag.KategoriAdi = _kategoriRepository.Get(q => q.SeoSlug == "ziyaretler").Ad;
            return View(viewModelYayin);
        }

        public ActionResult YayinDetay(string slugUrl,string slugKategori)
        {
            var cyayin =  _yayinRepository.Get(q => q.SeoSlug == slugUrl&&q.Kategori.SeoSlug==slugKategori);
            var viewModelYayinlar = (from yayin in _yayinRepository.GetAll()
                                  orderby yayin.YayinTarihi descending
                                  select new ViewModelYayin
                                  {
                                      ID = yayin.ID,
                                      KategoriID = yayin.KategoriId,
                                      KategoriAdi = yayin.Kategori.Ad,
                                      SeoSlugKategori = yayin.Kategori.SeoSlug,
                                      Baslik = yayin.Baslik,
                                      Icerik = yayin.Icerik,
                                      KisaAciklama = yayin.KisaAciklama,
                                      ResimKucuk = yayin.ResimUrlKucuk,
                                      ResimBuyuk = yayin.ResimUrlBuyuk,
                                      Resimler = yayin.Resimler.ToList(),
                                      Durumu = yayin.AktifMi,
                                      Siralama = yayin.Siralama,
                                      SeoSlug = yayin.SeoSlug,
                                      YayinTarihi = yayin.YayinTarihi
                                  }).Take(3);
            ViewBag.SonYayinlar = viewModelYayinlar;
            ViewBag.KategoriAdi = _kategoriRepository.Get(q => q.SeoSlug == slugKategori).Ad;
            if (cyayin == null)
            {
                return View(new ViewModelYayin());
            }
            else
            {
                var viewModelYayin = new ViewModelYayin
                {
                    ID = cyayin.ID,
                    KategoriID = cyayin.KategoriId,
                    KategoriAdi = cyayin.Kategori.Ad,
                    Baslik = cyayin.Baslik,
                    Icerik = cyayin.Icerik,
                    KisaAciklama = cyayin.KisaAciklama,
                    ResimKucuk = cyayin.ResimUrlKucuk,
                    ResimBuyuk = cyayin.ResimUrlBuyuk,
                    Resimler = cyayin.Resimler.ToList(),
                    Durumu = cyayin.AktifMi,
                    Siralama = cyayin.Siralama,
                    SeoSlug = cyayin.SeoSlug,
                    YayinTarihi = cyayin.YayinTarihi
                };
                return View(viewModelYayin);
            }
           
        }
    }
}

TurkKizilayi.Web/Areas/KizilayAdmin/Views/Shared/_Header.cshtml
@using Altyapi.Data.Model
@{
    var kullaniciModel = (Kullanici)Session["Kullanici"];
}

<header class="header">
    <div class="logo-container">
        <a href="../" class="logo">
            <img src="~/Content/img/logo.png" height="40" alt="Kızılay Admin" />
        </a>
        <div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <!-- start: user box -->
    <div class="header-right">

        <span class="separator"></span>

        <div id              ="userbox" class="userbox">
            <a href          ="#" data-toggle="dropdown">
                <figure class="profile-picture">
                    <img src ='@(kullaniciModel.ResimKucuk == null ? "../../Content/img/avatar.png" : kullaniciModel.ResimKucuk)' alt="@kullaniciModel.AdSoyad" data-lock-picture="@(kullaniciModel.ResimKucuk == null ? "../../Content/img/avatar.png" : kullaniciModel.ResimKucuk)"/>
                </figure>
                <div class="profile-info" data-lock-name="@kullaniciModel.AdSoyad" data-lock-email="@kullaniciModel.Eposta">
                    <span class="name">@kullaniciModel.AdSoyad</span>
                    <span class="role">Yönetici</span>
                </div>

                <i class="fa custom-caret"></i>
            </a>

            <div class="dropdown-menu">
                <ul class="list-unstyled">
                    <li class="divider"></li>
                    <li>
                        <a role="menuitem" tabindex="1" href="#"><i class="fa fa-user"></i> Profil</a>
                    </li>
                    <li>
                        <a role="menuitem" tabindex="2" href="@Url.Action("SifreDegistir","Kullanici",new {ID=kullaniciModel.ID})"><i class="fa fa-unlock-alt"></i> Şifre Değiştir</a>
                    </li>
                    <li>
                        <a role="menuitem" tabindex="3" href="@Url.Action("Login","Account")"><i class="fa fa-power-off"></i> Çıkış</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- end: user box -->
</header>

TurkKizilayi.Web/Areas/KizilayAdmin/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="fixed">
<head>

    <!-- Basic -->
    <meta charset="UTF-8">

    <title>@ViewBag.Title</title>

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/bootstrap-datepicker/css/datepicker3.css" rel="stylesheet" />
    <link href="~/Scripts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Scripts/pnotify/pnotify.css" rel="stylesheet" />
    <link href="~/Scripts/nanoscroller/nanoscroller.css" rel="stylesheet" />
    <link href="~/Scripts/magnific-popup/magnific-popup.css" rel="stylesheet" />
    <!-- Specific Page Vendor CSS -->
    <link href="~/Scripts/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />

    <!-- Theme CSS -->
    <link href="~/Content/css/theme.admin.css" rel="stylesheet" />

    <!-- Skin CSS -->
    <link href="~/Content/css/skins/default.admin.css" rel="stylesheet"/>

    <!-- Custom CSS -->
    <link href="~/Content/css/custom.admin.css" rel="stylesheet" />

    <!-- Head Libs -->
    <script src="~/Scripts/modernizr/modernizr.js"></script>

</head>
<body>
    <section class="body">

        <!-- start: header -->
       @Html.Partial("_Header")
        <!-- end: header -->

        <div class="inner-wrapper">
            <!-- start: sidebar -->
            @Html.Partial("_SideBar")
            <!-- end: sidebar -->

            <section role="main" class="content-body">        
                    @RenderBody()                    
            </section>
        </div>
    </section>

    <!-- Vendor -->
    <script src="~/Scripts/jquery/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/bootstrap-datepicker/js/locales/bootstrap-datepicker.tr.js"></script>>
    <script src="~/Scripts/jquery-placeholder/jquery.placeholder.js"></script>
    <script src="~/Scripts/nanoscroller/nanoscroller.js"></script>
    <!-- Specific Page Vendor -->
    <script src="~/Scripts/magnific-popup/jquery.magnific-popup.js"></script>
    <script src="~/Scripts/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
    <script src="~/Scripts/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
    <script src="~/Scripts/pnotify/pnotify.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="~/Scripts/theme.admin.js"></script>

    <!-- Theme Custom -->
    <script src="~/Scripts/theme.admin.custom.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <!-- Theme Initialization Files -->
    <script src="~/Scripts/theme.init.js"></script>

    <script src="~/Scripts/global.admin.js"></script>
    <script src="~/Scripts/ui-elements/examples.modals.js"></script>
</body>
</html>

TurkKizilayi.Web/Areas/KizilayAdmin/Views/Shared/_SideBar.cshtml
<aside id="sidebar-left" class="sidebar-left">

	<div class="sidebar-header">
		<div class="sidebar-title">
			Menu
		</div>
		<div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
			<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
		</div>
	</div>

	<div class="nano">
		<div class="nano-content">
			<nav id="menu" class="nav-main" role="navigation">
				<ul class="nav nav-main">
					<li class="nav-active">
						<a href="/">
							<i class="fa fa-home" aria-hidden="true"></i>
							<span>Anasayfa</span>
						</a>
					</li>
					<li class="nav-parent">
						<a href="#">                            
							<i class="fa fa-circle-o" aria-hidden="true"></i>
							<span>Kategori Yönetimi</span>
						</a>
						<ul class="nav nav-children">							
							<li>
								<a href="@Url.Action("Listele","Kategori")">
									Kategori Listele
								</a>
							</li>
                       </ul>
                    </li>

				    <li class="nav-parent">
				        <a href="#">
				            <i class="fa fa-circle-o" aria-hidden="true"></i>
				            <span>Yayın Yönetimi</span>
				        </a>
				        <ul class="nav nav-children">
				            <li>
				                <a href="@Url.Action("Listele", "Yayin")">
				                    Yayın Listele
				                </a>
				            </li>
				        </ul>
				    </li>

				    <li class="nav-parent">
				        <a href="#">
				            <i class="fa fa-circle-o" aria-hidden="true"></i>
				            <span>Kullanıcı Yönetimi</span>
				        </a>
				        <ul class="nav nav-children">
				            <li>
				                <a href="@Url.Action("Listele", "Kullanici")">
				                    Kullanıcı Listele
				                </a>
				            </li>
				        </ul>
				    </li>

                    <li class="nav-parent">
                        <a href="#">
                            <i class="fa fa-circle-o" aria-hidden="true"></i>
                            <span>Rol Yönetimi</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="@Url.Action("Listele","Rol")">
                                    Rol Listele
                                </a>
                            </li>
                        </ul>
                    </li>

				</ul>
			</nav>
		</div>
	</div>

</aside>